#%RAML 1.0
title: student_new
/student_new:
  get:
    queryParameters:
      firstname:
        displayName: First Name
        type: string
        required: true
        example: "Vansh"
      lastname:
        displayName: Last Name
        type: string
        required: false
        example: "Chauhan"
      rollno:
        displayName: Roll No
        type: string
        required: false
        example: "1"
    responses:
      200:
        body:
          application/json:
            example: !include example.json